### ISSUE TITLE
No message should be able to crash GridNetwork

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/GridNetwork#13]
We should leverage the magic of try/catch to make sure that no message (and no possible error/stacktrace from a message) can cause GridNetwork to crash. We should only be able to kill the node by sshing in and kiling it.

**Comment by IonesioJunior** [comment]
Closed by  c807c7d32e3d886ec740901f42823d6e24a388f9 , 3685c6ce931a395abc70d151742b034dcb72c4ea, 1e3037f09d4f1ae25a8e941151480359d7ad6b82 and 5983bebbd01917dad42cb865597874d149037842
